/*
 Navicat Premium Data Transfer

 Source Server         : 本机
 Source Server Type    : MySQL
 Source Server Version : 50639
 Source Host           : localhost:3306
 Source Schema         : monitoring

 Target Server Type    : MySQL
 Target Server Version : 50639
 File Encoding         : 65001

 Date: 01/12/2020 10:51:00
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for MONITOR_ALARM_DEFINITION
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_ALARM_DEFINITION`;
CREATE TABLE `MONITOR_ALARM_DEFINITION`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `TYPE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '告警类型（SERVER、NET、INSTANCE、CUSTOM）',
  `FIRST_CLASS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '一级分类',
  `SECOND_CLASS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '二级分类',
  `THIRD_CLASS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '三级分类',
  `GRADE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '告警级别（INFO、WARN、ERROR、FATAL）',
  `CODE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '告警编码',
  `TITLE` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警标题',
  `CONTENT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警内容',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_CODE`(`CODE`) USING BTREE COMMENT '索引_告警编码'
) ENGINE = InnoDB AUTO_INCREMENT = 10 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '告警定义表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_ALARM_RECORD
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_ALARM_RECORD`;
CREATE TABLE `MONITOR_ALARM_RECORD`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `CODE` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警代码，使用UUID',
  `TYPE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警类型（SERVER、NET、INSTANCE、CUSTOM）',
  `WAY` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警方式（SMS、MAIL、...）',
  `LEVEL` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警级别（INFO、WARM、ERROR、FATAL）',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '告警时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '告警结果获取时间',
  `TITLE` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警标题',
  `CONTENT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警内容',
  `STATUS` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '告警发送状态（0：失败；1：成功）',
  `NUMBER` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '被告警人号码（手机号码、电子邮箱、...）',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_CODE`(`CODE`) USING BTREE COMMENT '索引_告警记录编码'
) ENGINE = InnoDB AUTO_INCREMENT = 499 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '告警记录表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG`;
CREATE TABLE `MONITOR_CONFIG`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `THRESHOLD` int(1) NULL DEFAULT NULL COMMENT '监控阈值（1到10，共10级，1>10，默认为5）',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_ALARM
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_ALARM`;
CREATE TABLE `MONITOR_CONFIG_ALARM`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ENABLE` int(1) NULL DEFAULT NULL COMMENT '监控告警是否打开',
  `LEVEL` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '监控告警级别，四级：INFO < WARN < ERROR < FATAL',
  `WAY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '监控告警方式(MAIL、SMS)，多种告警方式用英文分号隔开',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  CONSTRAINT `MONITOR_CONFIG_ALARM_CONFIG_FK` FOREIGN KEY (`ID`) REFERENCES `MONITOR_CONFIG` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控告警配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_ALARM_MAIL
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_ALARM_MAIL`;
CREATE TABLE `MONITOR_CONFIG_ALARM_MAIL`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `EMILLS` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '收件人邮箱地址，多个地址用英文分号隔开',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  CONSTRAINT `MONITOR_CONFIG_MAIL_CONFIG_ALARM_FK` FOREIGN KEY (`ID`) REFERENCES `MONITOR_CONFIG_ALARM` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控邮件告警配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_ALARM_SMS
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_ALARM_SMS`;
CREATE TABLE `MONITOR_CONFIG_ALARM_SMS`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PHONE_NUMBERS` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '手机号码，多个号码用英文分号隔开',
  `ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '短信接口地址',
  `PROTOCOL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '短信接口协议',
  `ENTERPRISE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '短信接口企业',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  CONSTRAINT `MONITOR_CONFIG_SMS_CONFIG_ALARM_FK` FOREIGN KEY (`ID`) REFERENCES `MONITOR_CONFIG_ALARM` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控短信告警配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_NET
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_NET`;
CREATE TABLE `MONITOR_CONFIG_NET`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ENABLE` int(255) NULL DEFAULT NULL COMMENT '网络告警是否打开',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  CONSTRAINT `MONITOR_CONFIG_NET_CONFIG_FK` FOREIGN KEY (`ID`) REFERENCES `MONITOR_CONFIG` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控网络配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_SERVER
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_SERVER`;
CREATE TABLE `MONITOR_CONFIG_SERVER`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ENABLE` int(1) NULL DEFAULT NULL COMMENT '是否监控服务器',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控服务器信息配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_SERVER_CPU
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_SERVER_CPU`;
CREATE TABLE `MONITOR_CONFIG_SERVER_CPU`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `OVERLOAD_THRESHOLD` double(8, 2) NULL DEFAULT NULL COMMENT '过载阈值',
  `LEVEL` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '监控级别',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控服务器CPU信息配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_SERVER_DISK
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_SERVER_DISK`;
CREATE TABLE `MONITOR_CONFIG_SERVER_DISK`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `OVERLOAD_THRESHOLD` double(8, 2) NULL DEFAULT NULL COMMENT '过载阈值',
  `LEVEL` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '监控级别',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控服务器磁盘信息配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_CONFIG_SERVER_MEMORY
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_CONFIG_SERVER_MEMORY`;
CREATE TABLE `MONITOR_CONFIG_SERVER_MEMORY`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `OVERLOAD_THRESHOLD` double(8, 0) NULL DEFAULT NULL COMMENT '过载阈值',
  `LEVEL` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '监控级别',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '插入时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控服务器内存信息配置表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_INSTANCE
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_INSTANCE`;
CREATE TABLE `MONITOR_INSTANCE`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `INSTANCE_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例ID',
  `ENDPOINT` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '端点（客户端<client>、代理端<agent>、服务端<server>）',
  `INSTANCE_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例名',
  `INSTANCE_DESC` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '应用实例描述',
  `IP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'IP地址',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `IS_ONLINE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用状态（0：离线，1：在线）',
  `LANGUAGE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '编程语言',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_INSTANCE_ID`(`INSTANCE_ID`) USING BTREE COMMENT '索引_应用实例ID'
) ENGINE = InnoDB AUTO_INCREMENT = 48 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '应用实例表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_JVM_CLASS_LOADING
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_JVM_CLASS_LOADING`;
CREATE TABLE `MONITOR_JVM_CLASS_LOADING`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `INSTANCE_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例ID',
  `TOTAL_LOADED_CLASS_COUNT` int(8) NULL DEFAULT NULL COMMENT '加载的类的总数',
  `LOADED_CLASS_COUNT` int(8) NULL DEFAULT NULL COMMENT '当前加载的类的总数',
  `UNLOADED_CLASS_COUNT` int(8) NULL DEFAULT NULL COMMENT '卸载的类总数',
  `IS_VERBOSE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否启用了类加载系统的详细输出',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_INSTANCE_ID`(`INSTANCE_ID`) USING BTREE COMMENT '索引_应用实例ID',
  CONSTRAINT `MONITOR_JVM_CLASS_LOADING_INSTANCE_FK` FOREIGN KEY (`INSTANCE_ID`) REFERENCES `MONITOR_INSTANCE` (`INSTANCE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 44 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'java虚拟机类加载信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_JVM_GARBAGE_COLLECTOR
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_JVM_GARBAGE_COLLECTOR`;
CREATE TABLE `MONITOR_JVM_GARBAGE_COLLECTOR`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `INSTANCE_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例ID',
  `GARBAGE_COLLECTOR_NO` int(8) NULL DEFAULT NULL COMMENT '内存管理器序号',
  `GARBAGE_COLLECTOR_NAME` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '内存管理器名称',
  `COLLECTION_COUNT` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'GC总次数',
  `COLLECTION_TIME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'GC总时间（毫秒）',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_INSTANCE_ID`(`INSTANCE_ID`) USING BTREE COMMENT '索引_应用实例ID',
  CONSTRAINT `MONITOR_JVM_GARBAGE_COLLECTOR_INSTANCE_FK` FOREIGN KEY (`INSTANCE_ID`) REFERENCES `MONITOR_INSTANCE` (`INSTANCE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 87 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'java虚拟机GC信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_JVM_MEMORY
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_JVM_MEMORY`;
CREATE TABLE `MONITOR_JVM_MEMORY`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `INSTANCE_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例ID',
  `MEMORY_TYPE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '内存类型',
  `INIT` bigint(20) NULL DEFAULT NULL COMMENT '初始内存量（单位：byte）',
  `USED` bigint(20) NULL DEFAULT NULL COMMENT '已用内存量（单位：byte）',
  `COMMITTED` bigint(20) NULL DEFAULT NULL COMMENT '提交内存量（单位：byte）',
  `MAX` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最大内存量（单位：byte，可能存在未定义）',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_INSTANCE_ID`(`INSTANCE_ID`) USING BTREE COMMENT '索引_应用实例ID',
  CONSTRAINT `MONITOR_JVM_MEMORY_INSTANCE_FK` FOREIGN KEY (`INSTANCE_ID`) REFERENCES `MONITOR_INSTANCE` (`INSTANCE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 21409 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'java虚拟机内存信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_JVM_RUNTIME
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_JVM_RUNTIME`;
CREATE TABLE `MONITOR_JVM_RUNTIME`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `INSTANCE_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例ID',
  `NAME` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '正在运行的Java虚拟机名称',
  `VM_NAME` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机实现名称',
  `VM_VENDOR` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机实现供应商',
  `VM_VERSION` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机实现版本',
  `SPEC_NAME` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机规范名称',
  `SPEC_VENDOR` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机规范供应商',
  `SPEC_VERSION` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机规范版本',
  `MANAGEMENT_SPEC_VERSION` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '管理接口规范版本',
  `CLASS_PATH` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Java类路径',
  `LIBRARY_PATH` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Java库路径',
  `IS_BOOT_CLASS_PATH_SUPPORTED` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机是否支持引导类路径',
  `BOOT_CLASS_PATH` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '引导类路径',
  `INPUT_ARGUMENTS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Java虚拟机入参',
  `UPTIME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Java虚拟机的正常运行时间（毫秒）',
  `START_TIME` datetime(0) NULL DEFAULT NULL COMMENT 'Java虚拟机的开始时间',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_INSTANCE_ID`(`INSTANCE_ID`) USING BTREE COMMENT '索引_应用实例ID',
  CONSTRAINT `MONITOR_JVM_RUNTIME_INSTANCE_FK` FOREIGN KEY (`INSTANCE_ID`) REFERENCES `MONITOR_INSTANCE` (`INSTANCE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 48 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'java虚拟机运行时信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_JVM_THREAD
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_JVM_THREAD`;
CREATE TABLE `MONITOR_JVM_THREAD`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键IO',
  `INSTANCE_ID` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '应用实例ID',
  `THREAD_COUNT` int(8) NULL DEFAULT NULL COMMENT '当前活动线程数',
  `PEAK_THREAD_COUNT` int(8) NULL DEFAULT NULL COMMENT '线程峰值',
  `TOTAL_STARTED_THREAD_COUNT` int(8) NULL DEFAULT NULL COMMENT '已创建并已启动的线程总数',
  `DAEMON_THREAD_COUNT` int(8) NULL DEFAULT NULL COMMENT '当前活动守护线程数',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_INSTANCE_ID`(`INSTANCE_ID`) USING BTREE COMMENT '索引_应用实例ID',
  CONSTRAINT `MONITOR_JVM_THREAD_INSTANCE_FK` FOREIGN KEY (`INSTANCE_ID`) REFERENCES `MONITOR_INSTANCE` (`INSTANCE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 44 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'java虚拟机线程信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_NET
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_NET`;
CREATE TABLE `MONITOR_NET`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `IP_SOURCE` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'IP地址（来源）',
  `IP_TARGET` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'IP地址（目的地）',
  `IP_DESC` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP地址描述',
  `INSERT_TIME` datetime(0) NOT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `STATUS` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '状态（0：网络不通，1：网络正常）',
  `IS_ALARM` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '是否已经断网告警（0：否，1：是）',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_IP_SOURCE`(`IP_SOURCE`) USING BTREE COMMENT '索引_IP地址（来源）',
  INDEX `NX_IP_TARGET`(`IP_TARGET`) USING BTREE COMMENT '索引_IP地址（目的地）'
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '网络信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_ROLE
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_ROLE`;
CREATE TABLE `MONITOR_ROLE`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ROLE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色名称',
  `CREATE_TIME` datetime(0) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控用户角色表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_SERVER
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_SERVER`;
CREATE TABLE `MONITOR_SERVER`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `IP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP地址',
  `SERVER_NAME` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '服务器名',
  `OS_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '操作系统名称',
  `OS_VERSION` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '操作系统版本',
  `USER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户名称',
  `USER_HOME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户主目录',
  `OS_TIME_ZONE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '操作系统时区',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_IP`(`IP`) USING BTREE COMMENT '索引_IP'
) ENGINE = InnoDB AUTO_INCREMENT = 44 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '服务器表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_SERVER_CPU
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_SERVER_CPU`;
CREATE TABLE `MONITOR_SERVER_CPU`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `IP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP地址',
  `CPU_NO` int(8) NULL DEFAULT NULL COMMENT 'CPU序号',
  `CPU_MHZ` int(11) NULL DEFAULT NULL COMMENT 'CPU频率（MHz）',
  `CPU_VENDOR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'CPU卖主',
  `CPU_MODEL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'CPU的类别，如：Celeron',
  `CPU_USER` double(16, 4) NULL DEFAULT NULL COMMENT 'CPU用户使用率',
  `CPU_SYS` double(16, 4) NULL DEFAULT NULL COMMENT 'CPU系统使用率',
  `CPU_WAIT` double(16, 4) NULL DEFAULT NULL COMMENT 'CPU等待率',
  `CPU_NICE` double(16, 4) NULL DEFAULT NULL COMMENT 'CPU错误率',
  `CPU_COMBINED` double(16, 4) NULL DEFAULT NULL COMMENT 'CPU使用率',
  `CPU_IDLE` double(16, 4) NULL DEFAULT NULL COMMENT 'CPU剩余率',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_IP`(`IP`) USING BTREE COMMENT '索引_IP地址',
  CONSTRAINT `MONITOR_SERVER_CPU_SERVER_FK` FOREIGN KEY (`IP`) REFERENCES `MONITOR_SERVER` (`IP`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 21561 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '服务器CPU表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_SERVER_DISK
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_SERVER_DISK`;
CREATE TABLE `MONITOR_SERVER_DISK`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `IP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP地址',
  `DISK_NO` int(8) NULL DEFAULT NULL COMMENT '磁盘序号',
  `DEV_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分区的盘符名称',
  `DIR_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分区的盘符路径',
  `TYPE_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '磁盘类型名，比如本地硬盘、光驱、网络文件系统等',
  `SYS_TYPE_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '磁盘类型，比如 FAT32、NTFS',
  `TOTAL` bigint(20) NULL DEFAULT NULL COMMENT '磁盘总大小（单位：byte）',
  `FREE` bigint(20) NULL DEFAULT NULL COMMENT '磁盘剩余大小（单位：byte）',
  `USED` bigint(20) NULL DEFAULT NULL COMMENT '磁盘已用大小（单位：byte）',
  `AVAIL` bigint(20) NULL DEFAULT NULL COMMENT '磁盘可用大小（单位：byte）',
  `USE_PERCENT` double(16, 4) NULL DEFAULT NULL COMMENT '磁盘资源的利用率',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_IP`(`IP`) USING BTREE COMMENT '索引_IP',
  CONSTRAINT `MONITOR_SERVER_DISK_SERVER_FK` FOREIGN KEY (`IP`) REFERENCES `MONITOR_SERVER` (`IP`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 10906 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '服务器磁盘表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_SERVER_MEMORY
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_SERVER_MEMORY`;
CREATE TABLE `MONITOR_SERVER_MEMORY`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `IP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP地址',
  `MEM_TOTAL` bigint(20) NULL DEFAULT NULL COMMENT '物理内存总量（单位：byte）',
  `MEM_USED` bigint(20) NULL DEFAULT NULL COMMENT '物理内存使用量（单位：byte）',
  `MEM_FREE` bigint(20) NULL DEFAULT NULL COMMENT '物理内存剩余量（单位：byte）',
  `MEN_USED_PERCENT` double(16, 4) NULL DEFAULT NULL COMMENT '物理内存使用率',
  `SWAP_TOTAL` bigint(20) NULL DEFAULT NULL COMMENT '交换区总量（单位：byte）',
  `SWAP_USED` bigint(20) NULL DEFAULT NULL COMMENT '交换区使用量（单位：byte）',
  `SWAP_FREE` bigint(20) NULL DEFAULT NULL COMMENT '交换区剩余量（单位：byte）',
  `SWAP_USED_PERCENT` double(16, 4) NULL DEFAULT NULL COMMENT '交换区使用率',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_IP`(`IP`) USING BTREE COMMENT '索引_IP',
  CONSTRAINT `MONITOR_SERVER_MEMORY_SERVER_FK` FOREIGN KEY (`IP`) REFERENCES `MONITOR_SERVER` (`IP`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 2696 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '服务器内存表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_SERVER_NETCARD
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_SERVER_NETCARD`;
CREATE TABLE `MONITOR_SERVER_NETCARD`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `IP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP地址',
  `NET_NO` int(8) NULL DEFAULT NULL COMMENT '网卡序号',
  `NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网卡名字',
  `TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网卡类型',
  `ADDRESS` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网卡地址',
  `MASK` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '子网掩码',
  `BROADCAST` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '广播地址',
  `HW_ADDR` varchar(17) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'MAC地址',
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网卡信息描述',
  `RX_BYTES` bigint(20) NULL DEFAULT NULL COMMENT '接收到的总字节数',
  `RX_PACKETS` bigint(20) NULL DEFAULT NULL COMMENT '接收的总包数',
  `RX_ERRORS` bigint(20) NULL DEFAULT NULL COMMENT '接收到的错误包数',
  `RX_DROPPED` bigint(20) NULL DEFAULT NULL COMMENT '接收时丢弃的包数',
  `TX_BYTES` bigint(20) NULL DEFAULT NULL COMMENT '发送的总字节数',
  `TX_PACKETS` bigint(20) NULL DEFAULT NULL COMMENT '发送的总包数',
  `TX_ERRORS` bigint(20) NULL DEFAULT NULL COMMENT '发送时的错误包数',
  `TX_DROPPED` bigint(20) NULL DEFAULT NULL COMMENT '发送时丢弃的包数',
  `INSERT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '新增时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_IP`(`IP`) USING BTREE COMMENT '索引_IP',
  CONSTRAINT `MONITOR_SERVER_NETCARD_SERVER_FK` FOREIGN KEY (`IP`) REFERENCES `MONITOR_SERVER` (`IP`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 80 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '服务器网卡表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for MONITOR_USER
-- ----------------------------
DROP TABLE IF EXISTS `MONITOR_USER`;
CREATE TABLE `MONITOR_USER`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ACCOUNT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '账号',
  `USERNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密码',
  `ROLE_ID` bigint(20) NOT NULL COMMENT '角色ID',
  `REGISTER_TIME` datetime(0) NOT NULL COMMENT '注册时间',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `EMAIL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '电子邮箱',
  `REMARKS` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `NX_USER_ROLE_ID`(`ROLE_ID`) USING BTREE COMMENT '索引_角色ID',
  CONSTRAINT `MONITOR_USER_ROLE_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `MONITOR_ROLE` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 22 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '监控用户表' ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS = 1;
