DELETE FROM MONITOR_INSTANCE;
DELETE FROM MONITOR_NET;

DELETE FROM MONITOR_SERVER_CPU;
DELETE FROM MONITOR_SERVER_DISK;
DELETE FROM MONITOR_SERVER_MEMORY;
DELETE FROM MONITOR_SERVER_NETCARD;
DELETE FROM MONITOR_SERVER;

DELETE FROM MONITOR_JVM_CLASS_LOADING;
DELETE FROM MONITOR_JVM_GARBAGE_COLLECTOR;
DELETE FROM MONITOR_JVM_MEMORY;
DELETE FROM MONITOR_JVM_RUNTIME;
DELETE FROM MONITOR_JVM_THREAD;

ALTER TABLE MONITOR_INSTANCE AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_NET AUTO_INCREMENT = 1;

ALTER TABLE MONITOR_SERVER_CPU AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_SERVER_DISK AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_SERVER_MEMORY AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_SERVER_NETCARD AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_SERVER AUTO_INCREMENT = 1;

ALTER TABLE MONITOR_JVM_CLASS_LOADING AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_JVM_GARBAGE_COLLECTOR AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_JVM_MEMORY AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_JVM_RUNTIME AUTO_INCREMENT = 1;
ALTER TABLE MONITOR_JVM_THREAD AUTO_INCREMENT = 1;