--------------------------------------------------------
--  文件已创建 - 星期四-四月-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MONITOR_ALARM_DEFINITION
--------------------------------------------------------

  CREATE TABLE "OMS"."MONITOR_ALARM_DEFINITION" 
   (	"ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(8 BYTE), 
	"FIRST_CLASS" VARCHAR2(255 BYTE), 
	"SECOND_CLASS" VARCHAR2(255 BYTE), 
	"THIRD_CLASS" VARCHAR2(255 BYTE), 
	"GRADE" VARCHAR2(5 BYTE), 
	"CODE" VARCHAR2(8 BYTE), 
	"DEFINITION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OMS" ;

   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."ID" IS '主键';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."TYPE" IS '类型';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."FIRST_CLASS" IS '一级分类';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."SECOND_CLASS" IS '二级分类';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."THIRD_CLASS" IS '三级分类';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."GRADE" IS '告警级别';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."CODE" IS '告警编码';
   COMMENT ON COLUMN "OMS"."MONITOR_ALARM_DEFINITION"."DEFINITION" IS '告警定义';
--------------------------------------------------------
--  DDL for Index MONITOR_ALARM_DEFINITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMS"."MONITOR_ALARM_DEFINITION_PK" ON "OMS"."MONITOR_ALARM_DEFINITION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OMS" ;
--------------------------------------------------------
--  Constraints for Table MONITOR_ALARM_DEFINITION
--------------------------------------------------------

  ALTER TABLE "OMS"."MONITOR_ALARM_DEFINITION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OMS"."MONITOR_ALARM_DEFINITION" ADD CONSTRAINT "MONITOR_ALARM_DEFINITION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OMS"  ENABLE;
