##############################################server配置#################################################
server:
  servlet:
    context-path: /monitoring-agent
  undertow:
    accesslog:
      #Undertow日志存放目录
      dir: logs/monitoring-agent
      #是否启动日志
      enabled: true 
      #日志格式
      pattern: common
      #日志文件名前缀
      #prefix: access_log
      #日志文件名后缀
      #suffix: log

  
###############################################spring配置#################################################
spring:
  #main:
    #支持名称相同的bean的覆盖
    #allow-bean-definition-overriding: true
  application:
    name: monitoring-agent
  profiles:
    active:
    - dev
  devtools:
    livereload:
      port: 35730


############################################springboot端点配置#############################################
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
  server:
    #处于安全考虑，只允许在本地进行关闭操作
    address: 127.0.0.1