##############################################server配置#################################################
server:
  port: 12000


###############################################日志配置####################################################
logging:
  config: classpath:log-prod.xml
  #监控相关的日志级别设置成debug
  level:
    com.gitee.pifeng: debug