##############################################server配置#################################################
server:
  port: 12000


###############################################日志配置####################################################     
logging:
  config: classpath:log-dev.xml