##############################################server配置#################################################
server:
  port: 16000


###############################################日志配置####################################################
logging:
  config: classpath:log-prod.xml